---

# OpenStack Installer
tripleo: true

# Home directory on undercloud
home_dir: /home/stack

# Login user for the remote hosts
host_remote_user: heat-admin
# Login user for the local/jump machine
local_remote_user: stack

# The Overcloud RC file
overcloudrc:  ~/overcloudrc

# The Overcloud CA cert file
# overcloud_ca_path: /etc/pki/ca-trust/source/anchors/overcloud.crt.pem




########################################
# Collectd Configuration
########################################
# Interval in seconds
collectd_interval: 10
# Run collectd on specific openstack nodes:
collectd_undercloud: true
collectd_controller: true
collectd_ceph: false
collectd_compute: true





