---
#
# Install/run grafana-server for browbeat
#

- name: disable firewalld
  service: name=firewalld state=stopped enabled=false
  become: true
  ignore_errors: true

- name: Install repo file for docker
  copy:
    src=docker.repo
    dest=/etc/yum.repos.d/docker.repo
    owner=root
    group=root
    mode=0644
  become: true

- name: Install docker rpm
  yum: name={{ item }} state=present
  become: true
  with_items:
    - docker-engine

# Start docker service

- name: Setup docker service
  service: name=docker state=started enabled=true
  become: true

- name: ensure data directory exists
  file: path={{ persistent_grafana_data_path }} state=directory mode=0777

- name: ensure docker overrides for carbon-cache
  file: path=/etc/docker/grafana state=directory mode=0755

- name: Install docker-ps script
  copy:
    src=docker-ps-names.sh
    dest=/usr/local/bin/docker-ps-names.sh
    owner=root
    group=root
    mode=0755
  become: true

- name: check active containers
  command: /usr/local/bin/docker-ps-names.sh
  register: docker_ps_a

- name: start grafana docker container
  command: "{{item}}"
  ignore_errors: true
  with_items:
    - docker kill grafana
    - docker rm grafana
    - docker run -d --name grafana -p {{ docker_grafana_port }}:3000 -v {{ persistent_grafana_data_path }}:/var/lib/grafana {{ grafana_docker_image }}
  when: '"grafana" not in docker_ps_a.stdout'

- name: Setup grafana systemd config
  template:
    src=grafana-server.service.j2
    dest=/etc/systemd/system/grafana-server.service
    owner=root
    group=root
    mode=0644
  become: true
  register: systemd_grafana_needs_restart

- name: bounce systemd and grafana-server container
  shell: /usr/bin/systemctl daemon-reload && /usr/bin/systemctl enable grafana-server && /usr/bin/systemctl restart grafana-server
  become: true
  when: systemd_grafana_needs_restart.changed

