---
#
# Playbook to install connmon on undercloud/overcloud
#

- hosts: undercloud
  remote_user: "{{ local_remote_user }}"
  vars:
    undercloud: true
  roles:
  - common
  - connmon

- hosts: controller
  remote_user: "{{ host_remote_user }}"
  vars:
    undercloud: false
  roles:
  - common
  - connmon
  - nova
  - neutron
  - keystone
  - cinder
  - heat
