---
#
# Install/run collectd for browbeat
#

#
# (akrzos) yum module works at this point due to the fact the EPEL repo now exists.  EPEL rpm is
# installed at this point in time.
#
- name: Install collectd rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - collectd
    - collectd-turbostat
    - collectd-mysql

# Get mysql's root password
- name: (Controllers Only) Get mysql root password
  command: hiera mysql::server::root_password
  become: true
  register: mysql_root_password
  when: "'controller' in group_names"

- name: Configure collectd.conf
  template:
    src={{config_type}}.collectd.conf.j2
    dest=/etc/collectd.conf
    owner=root
    group=root
    mode="0644"
  become: true

- name: Copy collectd-redis.sh
  copy:
    src=collectd-redis.sh
    dest=/usr/local/bin/collectd-redis.sh
    owner=root
    group=root
    mode="0755"
  become: true

#
# Configure selinux bits
#
- name: Check for collectd permissive
  shell: semodule -l | grep -q permissive_collectd_t
  become: true
  register: collectd_permissive
  ignore_errors: true
  changed_when: false

- name: Set permissive for collectd
  command: semanage permissive -a collectd_t
  become: true
  when: collectd_permissive.rc != 0

#
# Additional policy bits may be needed for exec
#
- name: Collectd policy customization
  copy:
    src=custom-collectd.pp
    dest=/root/custom-collectd.pp
    owner=root
    group=root
    mode="0644"
  become: true

- name: Check for collectd custom
  shell: semodule -l | grep -q custom-collectd
  become: true
  register: collectd_custom
  ignore_errors: true
  changed_when: false

- name: Set custom policy for collectd
  command: semodule -i /root/custom-collectd.pp
  become: true
  when: collectd_custom.rc != 0

#
# Start collectd service
#
- name: Setup collectd service
  service: name=collectd state=restarted enabled=true
  become: true
