---
#
# Cinder handlers for browbeat install connmon
#

- name: unmanage cinder services
  command: pcs resource unmanage {{ item }}
  become: true
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume
  ignore_errors: true

- name: restart cinder services
  service: name={{ item }} state=restarted
  become: true
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume

- name: manage cinder services
  command: pcs resource manage {{ item }}
  become: true
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume
  ignore_errors: true

- name: cleanup cinder services
  command: pcs resource cleanup {{ item }}
  become: true
  with_items:
    - openstack-cinder-api
    - openstack-cinder-scheduler
    - openstack-cinder-volume
  ignore_errors: true
